<?php

use Utopia\Database\Database;
use Utopia\Database\Helpers\ID;

return [
    "todos" => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom("todos"),
        "name" => "todos",
        "tenant" => true,
        "attributes" => [
            [
                '$id' => ID::custom("title"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => APP_LIMIT_TODO_TITLE,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("description"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => APP_LIMIT_TODO_DESCRIPTION,
                "signed" => true,
                "required" => false,
                "default" => "",
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("completed"),
                "type" => Database::VAR_BOOLEAN,
                "format" => "",
                "size" => 0,
                "signed" => true,
                "required" => false,
                "default" => false,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("priority"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 32,
                "signed" => true,
                "required" => false,
                "default" => "normal",
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("ownerId"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 36,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
        ],
        "indexes" => [
            [
                '$id' => ID::custom("_key_completed"),
                "type" => Database::INDEX_KEY,
                "attributes" => ["completed"],
                "orders" => [Database::ORDER_ASC],
            ],
            [
                '$id' => ID::custom("_key_priority"),
                "type" => Database::INDEX_KEY,
                "attributes" => ["priority"],
                "orders" => [Database::ORDER_ASC],
            ],
            [
                '$id' => ID::custom("_createdAt"),
                "type" => Database::INDEX_KEY,
                "attributes" => ['$createdAt'],
                "orders" => [Database::ORDER_DESC],
            ],
        ],
    ],
    "tenants" => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom("tenants"),
        "name" => "tenants",
        "attributes" => [
            [
                '$id' => ID::custom("name"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => APP_LIMIT_TENANT_NAME,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("slug"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => APP_LIMIT_TENANT_SLUG,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("status"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 16,
                "signed" => true,
                "required" => false,
                "default" => "active",
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("ownerId"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 36,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
        ],
        "indexes" => [
            [
                '$id' => ID::custom("_key_slug"),
                "type" => Database::INDEX_UNIQUE,
                "attributes" => ["slug"],
                "orders" => [Database::ORDER_ASC],
            ],
        ],
    ],
    "users" => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom("users"),
        "name" => "users",
        "attributes" => [
            [
                '$id' => ID::custom("email"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => APP_LIMIT_USER_EMAIL,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("emailVerified"),
                "type" => Database::VAR_BOOLEAN,
                "format" => "",
                "size" => 0,
                "signed" => true,
                "required" => false,
                "default" => false,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("name"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => APP_LIMIT_USER_NAME,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("password"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => APP_LIMIT_USER_PASSWORD_HASH,
                "signed" => true,
                "required" => false,
                "default" => "",
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("status"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 16,
                "signed" => true,
                "required" => false,
                "default" => "active",
                "array" => false,
                "filters" => [],
            ],
        ],
        "indexes" => [
            [
                '$id' => ID::custom("_key_email"),
                "type" => Database::INDEX_UNIQUE,
                "attributes" => ["email"],
                "orders" => [Database::ORDER_ASC],
            ],
        ],
    ],
    "identities" => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom("identities"),
        "name" => "identities",
        "attributes" => [
            [
                '$id' => ID::custom("userId"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 36,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("provider"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 32,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("providerUserId"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 256,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("providerEmail"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => APP_LIMIT_USER_EMAIL,
                "signed" => true,
                "required" => false,
                "default" => "",
                "array" => false,
                "filters" => [],
            ],
        ],
        "indexes" => [
            [
                '$id' => ID::custom("_key_provider_uid"),
                "type" => Database::INDEX_UNIQUE,
                "attributes" => ["provider", "providerUserId"],
                "orders" => [Database::ORDER_ASC, Database::ORDER_ASC],
            ],
            [
                '$id' => ID::custom("_key_user"),
                "type" => Database::INDEX_KEY,
                "attributes" => ["userId"],
                "orders" => [Database::ORDER_ASC],
            ],
        ],
    ],
    "memberships" => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom("memberships"),
        "name" => "memberships",
        "attributes" => [
            [
                '$id' => ID::custom("tenantId"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 36,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("userId"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 36,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("role"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => APP_LIMIT_ROLE,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("status"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 16,
                "signed" => true,
                "required" => false,
                "default" => "active",
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("invitedBy"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 36,
                "signed" => true,
                "required" => false,
                "default" => "",
                "array" => false,
                "filters" => [],
            ],
        ],
        "indexes" => [
            [
                '$id' => ID::custom("_key_tenant_user"),
                "type" => Database::INDEX_UNIQUE,
                "attributes" => ["tenantId", "userId"],
                "orders" => [Database::ORDER_ASC, Database::ORDER_ASC],
            ],
            [
                '$id' => ID::custom("_key_tenant"),
                "type" => Database::INDEX_KEY,
                "attributes" => ["tenantId"],
                "orders" => [Database::ORDER_ASC],
            ],
            [
                '$id' => ID::custom("_key_user"),
                "type" => Database::INDEX_KEY,
                "attributes" => ["userId"],
                "orders" => [Database::ORDER_ASC],
            ],
        ],
    ],
    "sessions" => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom("sessions"),
        "name" => "sessions",
        "attributes" => [
            [
                '$id' => ID::custom("userId"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 36,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("secret"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => APP_LIMIT_SECRET_HASH,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("provider"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 32,
                "signed" => true,
                "required" => false,
                "default" => "email",
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("userAgent"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 512,
                "signed" => true,
                "required" => false,
                "default" => "",
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("ip"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 64,
                "signed" => true,
                "required" => false,
                "default" => "",
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("expire"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 64,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
        ],
        "indexes" => [
            [
                '$id' => ID::custom("_key_user"),
                "type" => Database::INDEX_KEY,
                "attributes" => ["userId"],
                "orders" => [Database::ORDER_ASC],
            ],
            [
                '$id' => ID::custom("_key_expire"),
                "type" => Database::INDEX_KEY,
                "attributes" => ["expire"],
                "orders" => [Database::ORDER_ASC],
            ],
        ],
    ],
    "tokens" => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom("tokens"),
        "name" => "tokens",
        "attributes" => [
            [
                '$id' => ID::custom("userId"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 36,
                "signed" => true,
                "required" => false,
                "default" => "",
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("type"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 32,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("secret"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => APP_LIMIT_SECRET_HASH,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("expire"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 64,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
        ],
        "indexes" => [
            [
                '$id' => ID::custom("_key_user"),
                "type" => Database::INDEX_KEY,
                "attributes" => ["userId"],
                "orders" => [Database::ORDER_ASC],
            ],
            [
                '$id' => ID::custom("_key_type"),
                "type" => Database::INDEX_KEY,
                "attributes" => ["type"],
                "orders" => [Database::ORDER_ASC],
            ],
        ],
    ],
    "migrations" => [
        '$collection' => ID::custom(Database::METADATA),
        '$id' => ID::custom("migrations"),
        "name" => "migrations",
        "attributes" => [
            [
                '$id' => ID::custom("name"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 255,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
            [
                '$id' => ID::custom("appliedAt"),
                "type" => Database::VAR_STRING,
                "format" => "",
                "size" => 64,
                "signed" => true,
                "required" => true,
                "default" => null,
                "array" => false,
                "filters" => [],
            ],
        ],
        "indexes" => [],
    ],
];
