<?php

const APP_NAME = 'Clarus Backend';
const APP_VERSION = '0.1.0';

const APP_LIMIT_ARRAY_PARAMS_SIZE = 100;
const APP_LIMIT_TODO_TITLE = 256;
const APP_LIMIT_TODO_DESCRIPTION = 4096;

const APP_DATABASE_TIMEOUT_MILLISECONDS = 15000;
const APP_DATABASE_QUERY_MAX_VALUES = 1000;
